---
# Role handlers

- name: gnu_linux reboot
  shell: >-
    sleep {{ gnu_linux_reboot_delay }}
    && shutdown -r now 'Ansible gnu_linux role triggered a reboot'
  async: 1
  poll: 0
  changed_when: true
  ignore_errors: true
  listen: reboot host
  when: ansible_virtualization_type | default("") != "docker"
  check_mode: no

- name: gnu_linux wait
  wait_for_connection:
    sleep: "{{ gnu_linux_wait_sleep }}"
    delay: "{{ gnu_linux_wait_delay }}"
    timeout: "{{ gnu_linux_wait_timeout | default(300) }}"
  changed_when: false
  listen: wait host
  check_mode: no

- name: gnu_linux pause
  pause:
    prompt: "Ansible gnu_linux role triggered a pause"
    seconds: "{{ gnu_linux_pause_time | default(5) }}"
  listen: pause host
  check_mode: no
