---
# Role handlers

- name: gnu_linux reboot
  command: shutdown -r +1 'Ansible gnu_linux role triggered a reboot'
  async: 0
  poll: 0
  changed_when: true
  ignore_errors: true
  listen: reboot host
  when: ansible_virtualization_type | default("") != "docker"
  check_mode: no

- name: gnu_linux wait
  wait_for:
    host: "{{ ansible_host }}"
    state: started
    port: "{{ gnu_linux_wait_port | default(ansible_port) | default(22) }}"
    delay: 5
    timeout: "{{ gnu_linux_wait_timeout | default(300) }}"
  changed_when: false
  listen: wait host
  check_mode: no

- name: gnu_linux pause
  pause:
    prompt: "Ansible gnu_linux role triggered a pause"
    seconds: "{{ gnu_linux_pause_time | default(5) }}"
  listen: pause host
  check_mode: no
